metadata:
  name: "hello"
  namespace: "argocd"
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
sample_version: "2"
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "harness-poc-dev"
  project: "default"
  source:
    repoURL: "https://cloudecho.github.io/charts"
    targetRevision: "0.1.2"
    chart: "hello"
    helm:
      releaseName: "hello"
